name: Android CI for Patch-2

on:
  push:
    branches: [ "bchiyanike-patch-2" ]
  pull_request:
    branches: [ "bchiyanike-patch-2" ]
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout patch-2
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.buildType && 'patch-2' }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build selected APK
        run: ./gradlew assemble${{ github.event.inputs.buildType == 'debug' && 'Debug' || 'Release' }}
