name: Android APK Release

on:
  push:
    branches: [main] # or your default branch
  pull_request:
    branches: [main] # optional: restrict to PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed to upload assets to the release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set JAVA_HOME explicitly
        run: echo "JAVA_HOME=${{ env.JAVA_HOME }}" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/*.apk
